# Generated by Django 2.0.5 on 2018-05-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rand_str',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='wechat_openid',
            field=models.TextField(default=''),
        ),
    ]
